language: objective-c
before_install: 
    - export LANG=en_US.UTF-8
    - rake install
script: 
    - rake clean:demo
	- rake build
notifications:
    email:
        recipients:
         - michael.gorbach@raizlabs.com
        on_success: change
        on_failure: always
